version: '3.8'

services:
    vemulator:
        container_name:   emulator
        image: 'budtmo/docker-android:emulator_11.0'
        ports:
            - '6080:6080'
            - '5555:5555'
        environment:
            - 'EMULATOR_DEVICE=Samsung Galaxy S7'
            - WEB_VNC=true
        devices:
            - /dev/kvm
        restart: unless-stopped
        healthcheck:
            test: 'cat /home/androidusr/device_status | grep "READY"'
            interval: 20s
            timeout: 10s
            retries: 15   
            start_period: 2ms         


    rn-app:
        container_name: react-native
        build:
            context: ./app
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./app/src:/usr/src/app
        restart: unless-stopped
        ports:
            - 3000:3000
            - 5000:5000
        command:
            - /bin/bash
            - -c
            - |
                npm install --legacy-peer-deps
                /android/sdk/platform-tools/adb connect vemulator:5555
                npm run android
        depends_on:
            - vemulator
        environment:
            - DB_HOST=mongodb
            - DB_NAME=recapsheet
            - WATCHPACK_POLLING=true 
        stdin_open: true
        tty: true



    # test:  ["CMD", "cat", "/home/androidusr/device_status", "|",  "grep", "READY"]
    # seed:
    #     image: mongo
    #     container_name: seed
    #     depends_on:
    #         - mongodb
    #     volumes:
    #         - ./jsondata:/jsondata
    #     command:
    #         - /bin/bash
    #         - -c
    #         - |
    #             mongoimport --jsonArray --uri "mongodb://mongodb:27017" -d recapsheet -c grades --file /jsondata/grades.json 
    #             mongoimport --jsonArray --uri "mongodb://mongodb:27017" -d recapsheet -c marks --file /jsondata/marks.json 
    #             mongoimport --jsonArray --uri "mongodb://mongodb:27017" -d recapsheet -c heads --file /jsondata/heads.json
    #             mongoimport --jsonArray --uri "mongodb://mongodb:27017" -d recapsheet -c students --file /jsondata/students.json
    



    # docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S7" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0
