FROM node:18
WORKDIR /android/sdk
RUN wget -q https://dl.google.com/android/repository/platform-tools-latest-linux.zip && \
	unzip -q platform-tools-latest-linux.zip && \
	rm platform-tools-latest-linux.zip